apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
{{- if eq .Release.Namespace "prod" }}
  minReplicas:   {{ index .Values.hpa.prod.minReplicas }}
  maxReplicas: {{ index .Values.hpa.prod.maxReplicas }}
{{- else if eq .Release.Namespace "stage" }}
  minReplicas:   {{ index .Values.hpa.stage.minReplicas }}
  maxReplicas: {{ index .Values.hpa.stage.maxReplicas }}
{{- else}}
  minReplicas:   {{ index .Values.hpa.uat.minReplicas }}
  maxReplicas: {{ index .Values.hpa.uat.maxReplicas }}
{{- end}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 230
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 500
