apiVersion: v1
kind: Secret
metadata:
    name: public-gateway
    namespace: uat1
stringData:
    APOLLO_ENGINE_API_KEY_encrypted: ENC[AES256_GCM,data:jpzCHo1j68m+UpPRwODATmQtVzhzIdRK69oR7I+s3q7tcBuVYnM8Z4NssOc5dkNGb7GP,iv:jdmD5eJuKTSpt8OkDQGLtDNM4rN8AP51EpilIa+yFN0=,tag:XqRj+0TzsJ3/bCysptScig==,type:str]
    SENTRY_DSN_encrypted: ENC[AES256_GCM,data:IZtPze9XE8S2PE7RbbcZjl1Tv2FrLI2+Q2Q0rZCrp6YNjfCIhue58pfw1xceuh7VILlTT/xGGvq9KR2VVtBXlju2rTJK4J4Pv8oBwqk1WioG6+QisYmOvOek,iv:8gcadv3YwNayGab2r1DT3e6UmAPqqXVGiVu/dxP61MA=,tag:lTlYxXUsmdR0jIVQkg6KYA==,type:str]
    AWS_S3_ACCESS_KEY_ID_encrypted: ENC[AES256_GCM,data:aIxHbefoUY9Ql9A4riy50HIlVNg=,iv:szHarq977aRVnfaWC4r9ikq1GjwsXQiusarSPcZBiE8=,tag:s9W7JHqBDxhb0dhZ/gLCQw==,type:str]
    AWS_S3_SECRET_ACCESS_KEY_encrypted: ENC[AES256_GCM,data:BN6tBOBflsR6z50tFvVgql6jKwfwp1fj6k4LDLZjXTkHXTTkK2kkpw==,iv:Z6OigiAyWVy/6Zlmk4pbFR8rz57ZzOmAIDl8MHE1Oac=,tag:jN6RReWqeNCWhdrDfWL+4w==,type:str]
    AWS_S3_OPPORTUNITY_DOCUMENT_KEY_encrypted: ENC[AES256_GCM,data:fIY8kZY7H5+xCe0+WIBnkMTPnDA=,iv:oRCjDRRWM25sW19HnWry3zCkgRDMA1nX5n1m55RfvnQ=,tag:i/AvMWbZGQeH3VEIQ2rTRg==,type:str]
    AWS_S3_OPPORTUNITY_DOCUMENT_SECRET_encrypted: ENC[AES256_GCM,data:3HSqixP4+R0Q52gyIgBiCPqWLGvd3A0B9Z62Te9hEYSmnF8SPtakHQ==,iv:SUuXZ7sEDNG3JvBehNZ5FEhu6L7Ee2OWGamuYdAiyHI=,tag:+hC2I+GUPdyUaVS4glmL9Q==,type:str]
    AWS_S3_STORM_FRONTEND_KEY_encrypted: ENC[AES256_GCM,data:AJGWLKfX0PRNdsXuMyTz7rCS9Ns=,iv:Kwh+KhJ1TroOO43ALE5DHmuvrorTCH6s7ZXOInyRP8s=,tag:8rK4B/MtraCQNBhQUMq02g==,type:str]
    AWS_S3_STORM_FRONTEND_SECRET_encrypted: ENC[AES256_GCM,data:APHIdZOWNtdPisa59E1ca/nexgGZEx6cyHMvrKp5H+hn0elsgv2KUw==,iv:/wvsnCJTuWvTN1n/bJBnGIDBuIoR4Vj6OO40MUegpt4=,tag:EsdpXO/XjQMrH4uFQwU/JA==,type:str]
type: Opaque
sops:
    kms:
    -   arn: arn:aws:kms:ap-southeast-1:091107424697:key/26f50d14-96bc-4cb9-a671-1380bb88b1de
        created_at: '2022-07-05T06:03:31Z'
        enc: AQICAHgndpQo/naUlbfArwkw0qgNfqTTI8eK3HHWyfgcNStYEQFcZQnuKGPWQm5pToZvKMmmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMC6T7DPvT9eB5XaXEAgEQgDsYEraxrlUv5rVRr5PT4ThRX47pkiTaxK/KmEWCCjreVvKZjLiRLAg2kheV3XyknE3lhf9yCEonJywCyg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-07-05T06:23:32Z'
    mac: ENC[AES256_GCM,data:dnrVbVK/n2hMjqunihmxwHAzAWbFZ3VK8PAwC/Z/oqTMQEFuJXz+1NpN5aX1sqWtugwIvCVuaL/gEUAS0i3z55bNC+vCsHpJJMZrXdCBUUQ44VK5aZFis9CV91rR1aTAOmK0ns+XdNUE6HBJKdn4/Qwygsj3pEa3CLNuCiVjOb0=,iv:9h1AL5S81upFoYqahbul4DKL0cIwhDY4LExr0tCQpI4=,tag:V/o6MIgCPtsMVHkECFX5Kg==,type:str]
    pgp: []
    encrypted_suffix: _encrypted
    version: 3.3.1
