apiVersion: v1
kind: Secret
metadata:
    name: public-gateway
    namespace: prod
stringData: null
type: Opaque
sops:
    kms:
    -   arn: arn:aws:kms:ap-southeast-1:091107424697:key/49a775e6-ab93-4125-ac6f-11dc9b5c777a
        created_at: '2022-07-05T05:59:56Z'
        enc: AQICAHiGpA2VJyT21AAWFjMHmjqXTUZ4DXpUvm1BOCEiSfkY4wFI/reOGoafIhX2hYHP7O7qAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUua4D2EQMfcFRYGBAgEQgDtqbFSfNIkqiGXpIy0jollwy4QpxDW/rT66QX78Yxe8RIbtzka+/LfhaYy9/76ji6edcTRAJn4YgquqIQ==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-07-05T06:00:25Z'
    mac: ENC[AES256_GCM,data:Z7Gev/yq1pmmGieDURqAxiGu3q4GuiFflhFU2Cy6CwHJJZlJ8Nt9DT49H1pt4IGleeWV6zlDKylO8B8OsArW3qOPpBheuUV0uy1YNV1uvjBFcztEtyt3Kguzym1bVm0MK21jR5CZtcvBiuky9w3RLOYn+moBbpZVDkAFSNss2EQ=,iv:m8dOo/RGjcqbwaZEP9sbcflE9Y8s4Fr+4E54ZsR704s=,tag:T5CEoXMqYwAJX03rlnNbtg==,type:str]
    pgp: []
    encrypted_suffix: _encrypted
    version: 3.3.1
