apiVersion: v1
kind: Secret
metadata:
    name: public-gateway
    namespace: stage
stringData: null
type: Opaque
sops:
    kms:
    -   arn: arn:aws:kms:ap-southeast-1:091107424697:key/9b0a600a-6ded-406e-9c1d-a78ecd182eb3
        created_at: '2022-07-05T06:03:26Z'
        enc: AQICAHhJLTAFvh1yqTbp/NuEXUrDUuI0NdZWZKSL5TJpUFkE2gEUc8h8GhY9KcMc1Y3PlhKYAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMn0/PCibRZvGah61UAgEQgDvs8vpzmtb615ohC/VRHFkGF4qck9zQ+yLNbsAMMDYWWiSJOZkDkOAosPD1YTX6BUNTNnaZWFJrWNkFhA==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-07-05T06:03:26Z'
    mac: ENC[AES256_GCM,data:utNQuPVA1YQrOuCWWMd/EoV+WFVUZfmwFDdKgP0cBNw/tclxi5h4l22GLz8Cga+MPW+o1zFnW8+CHXhKZLkYT+zkKtFBOstWFJlEgmmRrXVjp1rKFkRDSLw3N1kHfSOvEwyFTMI0JFfPEwgI3FqXJ/WlH9QKSeVQmo6Qybocrno=,iv:tM6CgCYqtdujTYBm7askWrvFechXdl68lQ5ft+sw1TE=,tag:XZeXBkGTg1A0iTr3H5zQpA==,type:str]
    pgp: []
    encrypted_suffix: _encrypted
    version: 3.3.1
