apiVersion: v1
kind: Secret
metadata:
    name: public-gateway
    namespace: stage
stringData:
    APOLLO_ENGINE_API_KEY_encrypted: ENC[AES256_GCM,data:/gCfAqXdkJlH5zY6/sfnrsX4XhjBeE8jdf81/VFG0EQNWX3CEmbHJc8MW4wUNw5CCZbbCb+O,iv:V1sqoCUi8AoR+2rkfDwF+0dO9h3lwT1Vpy6AMBLNDYA=,tag:lOb5dGdkp3UmiRCfnJrM+Q==,type:str]
    GRAPHIQL_OAUTH2_PROXY_CLIENT_ID_encrypted: ENC[AES256_GCM,data:AFx9x+SRa841fyWPoxptegpPEVw=,iv:Rs4tUln+MwBsDnmzxZ3BH5larV7njhfXwPNLqwOXnhc=,tag:YEdN6z0FZqk2OJvG6Bo0kA==,type:str]
    GRAPHIQL_OAUTH2_PROXY_CLIENT_SECRET_encrypted: ENC[AES256_GCM,data:aIffC+XYlhV/w1KZ6byV0q3T2rGuFIHEQapa9ZRvHJJP8lPVBxOqwA==,iv:ygON6J/U64OtbgQBE274oAggnKlKUC+MHc3ZDsGujxQ=,tag:PXSvH9FmONJ54lOcqIExKw==,type:str]
    GRAPHIQL_OAUTH2_PROXY_COOKIE_SECRET_encrypted: ENC[AES256_GCM,data:WsOw5HDVqqoprP/inIYKhwabP9iTET95Je2L3OyLrxA=,iv:Q/oSFeT+zSjHXg5am82wdBHmxLFVAEHf00D73mWpF78=,tag:neQNsan4F4NHoyhtjOK6xw==,type:str]
    PLAYGROUND_OAUTH2_PROXY_CLIENT_ID_encrypted: ENC[AES256_GCM,data:RwvRwej+BqgFShSeG9w9LbSB4x8=,iv:SJ7GUYn3Vlv/GTmpyDxv35viKsxQWyz28LeDd/bi3Hw=,tag:NddKVZOfOPc8AeZ9JGVOkg==,type:str]
    PLAYGROUND_OAUTH2_PROXY_CLIENT_SECRET_encrypted: ENC[AES256_GCM,data:JwPoCClTNJSlLZ5aWwTcUETu7iNFb5b2tZgi+imtAMRMTlVPgF8LqA==,iv:toPLE0TvwAVruvGYX8Bb0GImsj7AI5tJ5J3vWboRz0E=,tag:iRLncvJ/fg2GKRjZJK+d5A==,type:str]
    PLAYGROUND_OAUTH2_PROXY_COOKIE_SECRET_encrypted: ENC[AES256_GCM,data:uV1Bcw0wvwkau9ZsAowKEkLyk4yzI9zI,iv:q0LU4NVb4YsI1IwqTYnT64pZZuXggWoEaYFKZhoG+88=,tag:FoUDTZctLxkLZA+rkEn3YQ==,type:str]
    SENTRY_DSN_encrypted: ENC[AES256_GCM,data:FFsFJxkW7QELU3i7VDeNELLgO0uKNBfBY8j4lWgWzFBkZ5+tQmSDR4nRvE64rRV6hWJ/wzXyC9BqMUGISwjVr2gLVhjEjYm9qGt5SyoDMcB4iqS7tmtduDj3,iv:aMk4aEggkYchnqqk2r/ijVsxl2P899kyF2QqR4JkhfQ=,tag:GcjveS64dqbl4sfnCn9p+w==,type:str]
    VOYAGER_OAUTH2_PROXY_CLIENT_ID_encrypted: ENC[AES256_GCM,data:Oj+pwixzds++ittPXfeDNBCbU+0=,iv:A/CK83z1N2lU9fqZ18yzHo1Uqz0Pgx6f7oxaO94GW6I=,tag:UVQfi5GDblhEV4J6v80a3Q==,type:str]
    VOYAGER_OAUTH2_PROXY_CLIENT_SECRET_encrypted: ENC[AES256_GCM,data:5UyjjiEs0hY0Qy6qZvcbT0Qv19Tnrl617oy9WZR533SBMg7trVKlcg==,iv:27kPybTakdxJHYaTPL6p9BM4W8ZLC/itSV5EZQ0k9E4=,tag:XVqG/YbNMrD2b4yTmxo2BA==,type:str]
    VOYAGER_OAUTH2_PROXY_COOKIE_SECRET_encrypted: ENC[AES256_GCM,data:ZiYOJsxkMlEwyvsTAk0+pQv0J6o5QELtZRLmtranCI8=,iv:oXPOhELs7c0JnAf651emPw5zwfm5DhsPxVcLFNqYFVw=,tag:CzAJJgoBR90wyEcUyYnnIA==,type:str]
    AWS_S3_ACCESS_KEY_ID_encrypted: ENC[AES256_GCM,data:ZPJLau+w9dD/Hd4eAbPqRaE7sEs=,iv:xd7o2lkiAGNoRlNue0G1bon51x7cCW0hyNAm/+G+14g=,tag:HrTkITkU5kWTTjkbhLdB+Q==,type:str]
    AWS_S3_SECRET_ACCESS_KEY_encrypted: ENC[AES256_GCM,data:G6RGgv7n0e2TYXmyh9QeicSiE+OyaPvGN3plKi0BpzRV3sX0eR2zrQ==,iv:13soNIgGNPoKqSmr85W8NND3VYrC3vpOp4suQLzu63Y=,tag:XpKykx/in1pEzJQ95auleg==,type:str]
    AWS_S3_OPPORTUNITY_DOCUMENT_KEY_encrypted: ENC[AES256_GCM,data:RjVAr58pe4nqCg3ZUsgFKNIBOEw=,iv:dZiV32MiCLGibXuvL9BFytTqBPzFwwQ8D7+lEaO0Itg=,tag:7az7ld7XTb2nQosMo7WTOQ==,type:str]
    AWS_S3_OPPORTUNITY_DOCUMENT_SECRET_encrypted: ENC[AES256_GCM,data:qwK6FEL9oQegqrDuSL3G7gWayVWUOf3+remkMs+h6p2su4eg0aZ25w==,iv:/K6KAJ1IC4qnlG6ciqARvzjZzTcMDhTe/yKaPonhxKg=,tag:9bSod3F6ezwJy+kDXxeYNg==,type:str]
    AWS_S3_STORM_FRONTEND_KEY_encrypted: ENC[AES256_GCM,data:2gPHRfqB357RZVawTuAfeuSmON0=,iv:tZcYf8K1B7vcKDuTJIYc5sG/OCVEBB2UvADDdHRXQts=,tag:5HE9+fg6kQ70cbXuFAk8Yg==,type:str]
    AWS_S3_STORM_FRONTEND_SECRET_encrypted: ENC[AES256_GCM,data:ymiv5OpsbgTHQBBPcwFJm0bl+q3zM0zvjNuJRNa/wKC66hQJGPHy2w==,iv:jAoqwEooBZscRT3uQphffwWANOQ5KZrQC28sxfP1kNo=,tag:PwqPVhMOv+XO9b9vGxB49g==,type:str]
type: Opaque
sops:
    kms:
        - arn: arn:aws:kms:ap-southeast-1:091107424697:key/9b0a600a-6ded-406e-9c1d-a78ecd182eb3
          created_at: "2021-11-16T08:54:51Z"
          enc: AQICAHhJLTAFvh1yqTbp/NuEXUrDUuI0NdZWZKSL5TJpUFkE2gFxQQo+LppXZ0AyodBpfPxXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgAfY1Ys2TOVSwN6sAgEQgDsL+Uv+gOYes1WUOOW6P06Abb65m2GfWJWBhoA7g2FUgQRfJFrf+FlCBoVUNpnRSetii762TDq8Pz011g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-16T08:54:52Z"
    mac: ENC[AES256_GCM,data:Yg+ZO3Spn2385WOB4Cg9ix63sflpMEEe8olZ7uEq/YzA5pzosIFFIiyG/vOH/TfHmlqHtHQfNOTH/oCturwSGfPar9XrVV7T2c1WlQM5Sio+IJjFHV4FzjAPu4xd8/teYu5O0FV4UeAX8iZr+38PeaiPkq0J5WO0JnJfjE0/WYw=,iv:rK7VxViUL2UYfkbamkK/bXSsuSPbU1jziVHvRIrbVYo=,tag:nngwtZnr96ISSi1NKs/W2w==,type:str]
    pgp: []
    encrypted_suffix: _encrypted
    version: 3.7.1
