apiVersion: v1
kind: Secret
metadata:
    name: public-gateway
    namespace: uat3
stringData: null
type: Opaque
sops:
    kms:
    -   arn: arn:aws:kms:ap-southeast-1:091107424697:key/26f50d14-96bc-4cb9-a671-1380bb88b1de
        created_at: '2022-07-05T06:03:42Z'
        enc: AQICAHgndpQo/naUlbfArwkw0qgNfqTTI8eK3HHWyfgcNStYEQEp3Z26IfTLr395nF+Q4vQVAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpBB2timJ79fNVGfZAgEQgDsRU4b6xg0XXHYrwR5TtpDI1yk+lYe+5JMOfI63DxWDM+F93X4HrNwspBRMEXpoPgYzEHEoRvEL303EPA==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2022-07-05T06:03:42Z'
    mac: ENC[AES256_GCM,data:/DNuIDkoK1kSM+8bjdDJrCW0pcZsfjEGSf6TOvAcs/ky7qTkBOgqc/wFMcc5FDsAv1nv4yiVadZN0VMuyOGjs8bbPoWgznng+e1Y6tbq9uV8+ygaxggX4NnXr8V08nhRm9v7ToO8hGu50JWQQt/3UQPTNl9SxFfYI/5WLGLFB0s=,iv:e90H4/Yjp4UKr1e4tN/Enl/nlendq515FeU8SVQ7hck=,tag:kv2m+j8RVOAR662oOonbHQ==,type:str]
    pgp: []
    encrypted_suffix: _encrypted
    version: 3.3.1
